### ISSUE TITLE
Reduce memory usage?

### ISSUE THREAD

**Issue by CostaC** [avalanche123/Imagine#100]
I'm resizing and adding a border to a 1Mb image and the script uses about 80Mb.

Works fine on my local machine with php.ini > memory limit = 128M

But my shared host has it hardcoded to 64M  (can't change via .htaccess nor ini_set() )

So I get:

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 13219521 bytes) 

Is there any way to reduce Imagine's memory usage? Thanks!

**Comment by manu1222** [comment]
`unset($image)` isn't working for me, I have to use `ini_set('memory_limit', '1024M');` to make it work. But that has a limitation in itself, if inside loop there are more than 50 images each 3-7MB in size, it may break after allocating '1024M' but if I use `ini_set('memory_limit', '-1');` that is unlimited memory. It will never break but this is not the correct way of solving this issue because this unlimited memory allocation can cause other damage to the server as well. So what would be the best way to resolve it.
