### ISSUE TITLE
Imagick's resizeImage vs. thumbnailImage

### ISSUE THREAD

**Issue by kevujin** [avalanche123/Imagine#518]
I currently upgraded my Imagine library and discovered, that making thumbnails was changed from Imagick::thumbnailImage to Imagick::resizeImage.
That has some drawbacks I suppose:
- resizeImage is much slower than thumbnailImage
- resizeImage makes much bigger pictures

Without limiting number of threads, resizeImage often crashes (a problem of imagick - just to let you know) telling that "Maximum execution time of 30 seconds exceeded".

I suggest returning thumbnailImage for thumbnail function to Imagick\Image wrapper.

**Comment by lemorragia** [comment]
+1

i made a few tests (i'm using very big images, 150-200mb each) with the new implementation (in AbstractImage) and the old (0.50 version Imagick\Image->thumbnail()) and there's an big increase in performances (almost half the memory usage, and almost half the time taken for the resize operation)

**Comment by mlocati** [comment]
The problem is that `thumbnail()` works on a copy of the image, whereas `resize()` resizes the image itself.
This is useful when you have to generate multiple thumbnails without the need to reload the original image:

```php
$image = $imagine->open('./input.png');
$image->thumbnail($size1)->save('./thumbnail-1.png');
$image->thumbnail($size2)->save('./thumbnail-2.png');
```

This couldn't be done with `resize`, which modifies the size of original image.

BTW, I do agree that it'd be useful to have a way to tell `thumbnail()` that it should modify the original image instead of returning a new image instance (and I'm going to implement it).

**Comment by mlocati** [comment]
And about the performance of `Imagick::thumbnailImage()` vs `Imagick::resizeImage()`: Imagine switched in 328b178bad62d5e9442a47024a7a6de308b548b4 from the first to the second because of a greater control of the output quality. You can control the quality (and processing time) of the resize operation by using one of the `ImageInterface::FILTER_...` constants.

**Comment by mlocati** [comment]
See #694
