### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by burzum** [avalanche123/Imagine#521]
There is a huge amount of good PRs and an even bigger amount of issues that don't get any attention.

Why? Is the project dead?

I really consider switching to https://github.com/Intervention/image because of the lack of support for this lib. :(

**Comment by scoolen** [comment]
ping @avalanche123 @romainneutron

**Comment by avalanche123** [comment]
would you like to be the maintainer?

**Comment by scoolen** [comment]
Not sure if directed at me but:
No thanks, not at this time.

**Comment by burzum** [comment]
@avalanche123 well, not really, I'm involved a lot with CakePHP and my own plugins for it (there is an imagine plugin). But if you like you can give me permissions to merge PRs. There is a ton of them waiting for approval and I think there are a few good ones present.

Also I would like to set up Scrutinizer CI for the project besides Travis to get code coverage and code analysis and phpcs checks. Are you using the PSR standard?

**Comment by avalanche123** [comment]
@burzum sure, I'll add you to collaborators

**Comment by burzum** [comment]
Thank you! You don't have the time to maintain this project any more? :(

I don't mind helping out sometimes but it would be also great to have another person reviewing my own changes if I decide to do some.

Also how is your opinion on dropping support for php up to 5.5?

**Comment by avalanche123** [comment]
Yes, let's drop it. I don't mind reviewing your pull requests, you might have to ping me explicitly. Yes, I'd appreciate any help with maintenance that you can give.

**Comment by burzum** [comment]
OK, I'll let you know. So far I haven't had a need to fix anything inside the lib. :) Great work you've done so far!

**Comment by avalanche123** [comment]
Thanks!

**Comment by thePanz** [comment]
Thank you @burzum to take this project over! :)
Could you please tag a new release? :)

**Comment by burzum** [comment]
@thePanz I'm **not** taking it over, just trying to help out with the PR's and issues.

Not sure if it's OK to tag a new release, I prefer if the maintainer would do that. I don't want to make such decisions without the project lead.

**Comment by thePanz** [comment]
Ok, clear! :) Btw: seems that most of the tests are now failing due to a version mismatch :(
I guess this repo needs some more love.. I'll try to find some time to help you out here, is it Ok for you?

**Comment by burzum** [comment]
Sure! Just contact @avalanche123 and ask him if you can get collaborator rights as well.

**Comment by avalanche123** [comment]
@thePanz I've added you as a collaborator

**Comment by robfrawley** [comment]
@avalanche123 I've been one of the new maintainers of liip/imagine-bundle, and I'd love to help out with this project as well, if you need additional people still.

**Comment by avalanche123** [comment]
Great, invited you @robfrawley

**Comment by robfrawley** [comment]
Much appreciated. ;-)

**Comment by robfrawley** [comment]
A few quick questions for you @avalanche123 

- Why is `master` behind `develop` by over two years? Can you clarify the conventions you use for `master` and `develop` so I don't inadvertently go against your workflow? Or are you indifferent to how it is handled moving forward?
- Are you comfortable with me tagging a new release after a few important PRs are cleaned up and merged? Been a while: [see diff between develop and v0.6.3](https://github.com/avalanche123/Imagine/compare/v0.6.3...develop).
- I think you and @burzum have established an intent to support only php >=5.6 https://github.com/avalanche123/Imagine/issues/527#issue-204959905: sounds great to me! We should plan to do so on a `0.7` branch and leave `0.6.x` untouched, IMHO.
- Do you have a RTD hook setup for automatic deployment of the docs if the files are updated/changed?

Otherwise, thanks for your amazing for to-date. @burzum and @thePanz: feel free to use the PR "request review" feature if you'd like more than one "okay" on anything. I'll likely be using it to ping you guys as well.

**Comment by burzum** [comment]
@robfrawley do you have any idea why my changes here are still not made Travis to use the 5.3 version of phpunit? This is the last version that works with Imagine without throwing deprecation warnings. https://github.com/avalanche123/Imagine/pull/528

And I agree with your idea for the branches. :)

**Comment by romainneutron** [comment]
Hello, 

I'm very surprised to see some changes in Imagine today.

I'm particularly shocked by the amount of pull requests merged whereas they were not ready (not finalized, invalid CS, code not enough reviewed).
I'm even more shocked that nearly all of the PR have been merged while the Travis test suite was broken.

Since 2012, I write bugfixes, finalize people pull requests and make this project live with some best practices to guarantee a high quality library, as Bulat wrote it at its beginning.

That's true that I did not give feedback on every pull request or issue this two last years.
 - First, I do not work everyday with image manipulation like I was in 2012, I work on my personal free time on this library.
 - Second, I don't think all features belongs to Imagine. Some features might be third party libraries depending on Imagine. As discussed in https://github.com/avalanche123/Imagine/pull/339, I think we should open extension point instead of adding feature in this library. Most of new features should be hosted AND maintained outside of the library
Merging new features means **guarantee of maintenance**, and I don't see how anybody could maintain both Imagine AND new features if nobody has time.

I'm also surprised that after I gave lots of time to Imagine, I did not receive any mail or Twitter ping related to "how to proceed?" "How Imagine is maintained?".

After reviewing the latest merge and fixing the test suite, I do think that the following PR should be reverted:

https://github.com/avalanche123/Imagine/pull/449
https://github.com/avalanche123/Imagine/pull/464
https://github.com/avalanche123/Imagine/pull/490
https://github.com/avalanche123/Imagine/pull/500
https://github.com/avalanche123/Imagine/pull/505
https://github.com/avalanche123/Imagine/pull/513
https://github.com/avalanche123/Imagine/pull/525
https://github.com/avalanche123/Imagine/pull/526

These were not mergeables in their current state. And I'm not sure that all of them should be in Imagine

Last but not least, as the latest release is quite old and some features/bugfixes have been added since, it should be a good thing to start with a fresh release

Let's be clear : I'm not against new maintainers; I want that the library quality be taken into account.

**Comment by nicolas-grekas** [comment]
Can't agree more with @romainneutron 
People should be able to make a difference between a dead project - and a stable project - one that works well, achieved quality level and solved its problem well enough that it doesn't require much more.
I'm not saying that Imagine is a finished project - but at least it's in a stable state, a working one.
If someone wants to make it a living project, please, do not destroy it's quality/stability while doing so.

**Comment by robfrawley** [comment]
@romainneutron I'm in 100% agreeance here, hence #529. Thanks for taking care of it when I couldn't allocate the time to do so myself.

**Comment by robfrawley** [comment]
@romainneutron I'm in 100% agreeance here, hence #529. Thanks for taking care of it when I couldn't allocate the time to do so myself. I'd also like to point out that I did ask for feedback in this thread not two comments above yours, and no one has taken the time to respond, including yourself; I haven't touched a line of code yet due to this. Asking for someone to ping all maintainers on Twitter is a little unrealistic, though.

It is also important to note that your approach over the past 24 hours has been a little "harsh" or "unsympathetic". We should be pointing out errors like the multiple PR merges that occurred with a failing test suite, but we also don't want to drive people away who are learning and interested in helping. I understand you were in "damage control" mode, but let's try to "court" new maintainers and not scare them away.

It was a mistake on that person's part; let's not act like we all haven't done something in error or acted without the knowledge or context to do so. It should be treated as an opportunity to teach.

**Comment by romainneutron** [comment]
Merging 10+ PR on 3000 stars repo without taking care of the test suite is fully irresponsible.
I'm not harsh or unsympathetic; I'm seriously shocked by this behavior.
Period.

**Comment by robfrawley** [comment]
I'm simply pointing out that our conversation with people can either be constructive, instructive, and educational or not; you've clearly settled on the latter.

**Comment by mlocati** [comment]
I have to bump this issue because we need some PR to be merged. Should we fork this repository? Or the pull requests are going to be reviewed?
Thanks

**Comment by mlocati** [comment]
I'm trying to liven it up a bit.
