### ISSUE TITLE
doc ticket: meaning of inset / outbound

### ISSUE THREAD

**Issue by nicam** [avalanche123/Imagine#91]
Hey There

It's nowhere really explained which one is inset and which one is outbound. Adding that to the documentation would be very helpful.

Thank you.

Pascal Helfenstein

**Comment by mikl** [comment]
Sorry to be the necromancer here, but I've spent at least half an hour now, trying to figure out what outbound means, and I can't find anywhere in the docs where its described. It could just be my doc-reading-skills that are deficient, if so, my apologies for waking the dead bugs :)

**Comment by beryllium** [comment]
If I understand correctly, OUTBOUND will crop the thumbnail to fit the box (preserving the aspect ratio), but INSET will not crop it (resulting in Imagine trying to cram the whole image into the thumb, regardless of aspect ratio).

**OUTBOUND (left), INSET (right):**

<img width="556" alt="screen shot 2017-05-20 at 7 57 12 pm" src="https://cloud.githubusercontent.com/assets/602491/26280818/c6907f4e-3d96-11e7-89ad-5f01cff2228b.png">

**Code snippet for above:**
<img width="659" alt="screen shot 2017-05-20 at 7 57 18 pm" src="https://cloud.githubusercontent.com/assets/602491/26280819/c9bfdb24-3d96-11e7-95e1-9e77aba9e39c.png">

This came up because I was looking for a way to do an OUTBOUND cropped thumbnail, but anchored to the top of the image instead of the centre point. Haven't found an ideal solution yet.
